"""
Ковадло — чисте ядро для параметричного моделювання будівель.

Модуль 1: кімната і стіни (geometry, profile, materials, elements, wall, room).
Модуль 2: покриття плиткою (tile, grout, layout, surface, tiling).
Модуль 4: електропроводка (electrical_point, cable_route, electrical_norms,
electrical_group, wiring_plan).
Модуль 6: друковані плати (pcb_component, pcb_footprints, pcb_netlist,
pcb_norms, pcb_board, pcb_checks, pcb_report).
Модуль 7: база матеріалів (material_spec, material_database, material_seed,
material_selection, material_compare) — наскрізна, нею користуються стіни,
плитка, електрика й плати через посилання за іменем.
Модуль 8: інженерні системи (lighting, ventilation, climate, insulation,
fire_safety + відповідні *_norms) — той самий підхід, що й модуль 4:
точки на плані + траси + розрахунок.
Модуль 10: тривимірна геометрія (geometry3d, extrude, opening, wall3d,
slab3d, roof3d, building3d, volume_calc, mesh_export).

Жодної графіки тут немає навмисно: ядро лише рахує геометрію й площі,
а рендеринг/UI — це окремий шар, якого тут немає і не буде.
"""

from .geometry import (
    MM2_PER_M2,
    MM_PER_M,
    Point,
    Rect,
    clip_convex_polygon,
    decompose_rectilinear_polygon,
    point_in_polygon,
    polygon_area,
    polygon_perimeter,
    rotate_point,
    snap_angle,
    snap_point,
)
from .materials import Material
from .profile import (
    Profile,
    RectangularProfile,
    SteelAngleProfile,
    SteelChannelProfile,
    SteelPipeProfile,
)
from .elements import Element
from .wall import Wall
from .room import Room
from .tile import Tile
from .grout import Grout
from .layout import RowOffset, TileLayout
from .surface import Surface
from .tiling import TileCut, TilingResult, calculate_tiling, format_report
from .electrical_point import DEFAULT_POWER_W, ConsumptionPoint, PointKind
from .cable_route import CableRoute, build_route
from .electrical_norms import (
    AMPACITY_A,
    COPPER_RESISTIVITY_OHM_MM2_PER_M,
    MAX_VOLTAGE_DROP_PERCENT_DEFAULT,
    MIN_CROSS_SECTION_LIGHTING_MM2,
    MIN_CROSS_SECTION_POWER_MM2,
    STANDARD_BREAKER_RATINGS_A,
    STANDARD_CROSS_SECTIONS_MM2,
    VOLTAGE_V,
    PhaseType,
    calculate_current_a,
    rcd_required_for_kinds,
    select_breaker_rating_a,
    select_cross_section_mm2,
    voltage_drop_percent,
)
from .electrical_group import Group, GroupCalculation, calculate_group
from .wiring_plan import WiringPlan, format_wiring_report
from .pcb_component import Component, ComponentKind, Footprint, Pin, Unit as ComponentUnit
from .pcb_footprints import (
    CONNECTOR_PITCH_MM,
    DIP_PITCH_MM,
    DIP_ROW_SPACING_MM,
    SOIC_PITCH_MM,
    SOIC_ROW_SPACING_MM,
    THT_RESISTOR_SPACING_MM,
    connector_footprint,
    dip_footprint,
    soic_footprint,
    to92_footprint,
    two_pin_footprint,
)
from .pcb_netlist import Net, NetKind, Netlist, PinRef, ShortCircuit
from .pcb_norms import (
    CLEARANCE_TABLE_MM,
    DEFAULT_COPPER_THICKNESS_UM,
    DEFAULT_TEMPERATURE_RISE_C,
    MAX_TRACK_VOLTAGE_DROP_PERCENT_DEFAULT,
    MIN_TRACK_WIDTH_MM,
    Layer,
    min_clearance_mm,
    required_track_width_mm,
    track_resistance_ohm,
    track_voltage_drop_v,
)
from .pcb_norms import COPPER_RESISTIVITY_OHM_MM2_PER_M as PCB_COPPER_RESISTIVITY_OHM_MM2_PER_M
from .pcb_board import Board, Placement, Track, Via, build_track
from .pcb_checks import ClearanceViolation, RatsnestGap, clearance_violations, unrouted_connections
from .pcb_report import format_board_report
from .material_spec import Coverage, MaterialCategory, MaterialSpec, PriceInfo
from .material_database import MaterialDatabase
from .material_seed import build_default_database
from .material_selection import (
    SelectionCriteria,
    SelectionResult,
    select_materials,
    select_tile_adhesive_for_balcony,
)
from .material_compare import (
    ThermalComparison,
    ThermalLayerOption,
    compare_for_thermal_resistance,
    conductor_resistance_ohm,
    thermal_layer_option,
)
from .lighting_norms import (
    DEFAULT_MAINTENANCE_FACTOR,
    DEFAULT_UTILIZATION_FACTOR,
    RECOMMENDED_LUX,
    RoomPurpose,
)
from .lighting import (
    FixtureKind,
    LightFixture,
    LightingPlan,
    fixtures_needed,
    illuminance_lux,
    lighting_group,
    plan_lighting,
    required_luminous_flux_lm,
)
from .ventilation_norms import (
    AIR_CHANGES_PER_HOUR,
    AIR_DENSITY_KG_M3,
    DEFAULT_FRICTION_FACTOR,
    MAX_RECOMMENDED_VELOCITY_M_S,
    MINIMUM_EXHAUST_M3_H,
    STANDARD_FANS,
    STANDARD_ROUND_DUCT_DIAMETERS_MM,
    VentilatedRoomKind,
)
from .ventilation import (
    Duct,
    DuctShape,
    air_velocity_m_s,
    build_duct,
    pressure_loss_pa,
    required_airflow_m3_h,
    select_fan,
    select_round_duct_diameter_mm,
)
from .climate_norms import (
    AIR_VOLUMETRIC_HEAT_CAPACITY_WH_M3K,
    DEFAULT_INDOOR_TEMP_C,
    DESIGN_OUTDOOR_TEMP_C,
    STANDARD_AC_POWERS_KW,
    STANDARD_RADIATOR_POWERS_W,
    ClimateZone,
)
from .climate import (
    BuildingElement,
    HeatBalance,
    select_ac_power_kw,
    select_radiator_power_w,
    transmission_heat_loss_w,
    ventilation_heat_loss_w,
)
from .insulation import (
    RSE_WALL_M2K_W,
    RSI_WALL_M2K_W,
    WT2021_MAX_U_WALL_W_M2K,
    InsulationCheck,
    WallLayer,
    check_against_wt2021,
    condensation_risk_warnings,
    dew_point_c,
    insulation_cost_per_m2,
    layer_interface_temperatures_c,
    required_insulation_thickness_m,
    wall_thermal_resistance_m2k_w,
    wall_u_value_w_m2k,
)
from .fire_safety_norms import COVERAGE_AREA_M2, MAX_SPACING_M, WALL_CLEARANCE_M, DetectorKind
from .fire_safety import (
    FireDetector,
    auto_place_detectors,
    detectors_needed,
    loop_length_m,
    place_detectors_along_contour,
)
from .geometry3d import Face, Point3
from .extrude import extrude_contour_walls, extrude_flat_faces
from .opening import Opening, OpeningKind
from .wall3d import Wall3D
from .slab3d import Slab
from .roof3d import Roof, RoofType, build_gable_roof, build_shed_roof
from .building3d import Building, Storey, contours_match
from .volume_calc import (
    exterior_envelope_area_m2,
    room_volume_m3,
    wall_material_costs_pln,
    wall_material_volumes_m3,
)
from .mesh_export import Mesh, build_room_mesh
from .mechanics_norms import (
    DEFAULT_SAFETY_FACTOR,
    ELASTIC_MODULUS_MPA,
    GRAVITY_M_S2,
    MAX_DEFLECTION_RATIO,
    elastic_modulus_mpa_for,
)
from .steel_profiles import (
    AngleProfile,
    ChannelProfile,
    FlatBarProfile,
    IBeamProfile,
    RectTubeProfile,
    RoundBarProfile,
    RoundTubeProfile,
    StructProfile,
)
from .beam import (
    Beam,
    BeamCheckResult,
    LoadScheme,
    Structure,
    bending_moment_max_nmm,
    bending_stress_mpa,
    evaluate_beam,
    max_deflection_mm,
)
from .shaft import (
    Shaft,
    disk_moment_of_inertia_kg_m2,
    ring_moment_of_inertia_kg_m2,
    wheel_moment_of_inertia_kg_m2,
)
from .transmission import (
    BeltTransmission,
    DirectTransmission,
    GearboxTransmission,
    Transmission,
    power_w,
    rad_s_to_rpm,
    rpm_to_rad_s,
    torque_nm,
)
from .motor import (
    Motor,
    MotorKind,
    current_under_load_a,
    heat_dissipation_w,
    motor_pcb_track_width_mm,
    power_input_w,
    to_consumption_point as motor_to_consumption_point,
    torque_constant_nm_per_a,
)
from .kinematics import (
    available_force_n,
    can_move_mass,
    required_force_to_move_n,
    time_to_speed_s,
    wheel_angular_velocity_rad_s,
    wheel_linear_speed_m_s,
)
from .mechanics_report import format_beam_report, format_drive_report, format_structure_report
from .sensors import OutputType, Sensor, SensorKind
from .actuators import (
    Actuator,
    ActuatorKind,
    ActuatorLike,
    actuator_current_a,
    actuator_kind_label,
    actuator_voltage_v,
)
from .controller import Controller, ControllerCheckResult, ControllerSpec, PinIssue
from .automation_logic import (
    Action,
    Condition,
    MachineState,
    Rule,
    Scenario,
    TimerSpec,
    apply_step,
    expired_timers,
    find_dead_end_states,
    find_forbidden_rule_violations,
)
from .automation_sim import SimulationLogEntry, SimulationResult, SimulationStep, run_scenario
from .gate_automation import GateSystem, build_gate_scenario, gate_cycle_time_s, recommended_timeout_s
from .automation_report import (
    format_controller_report,
    format_gate_system_report,
    format_scenario_report,
    format_simulation_report,
)

__all__ = [
    "MM2_PER_M2",
    "MM_PER_M",
    "Point",
    "Rect",
    "clip_convex_polygon",
    "decompose_rectilinear_polygon",
    "point_in_polygon",
    "polygon_area",
    "polygon_perimeter",
    "rotate_point",
    "snap_angle",
    "snap_point",
    "Material",
    "Profile",
    "RectangularProfile",
    "SteelAngleProfile",
    "SteelChannelProfile",
    "SteelPipeProfile",
    "Element",
    "Wall",
    "Room",
    "Tile",
    "Grout",
    "RowOffset",
    "TileLayout",
    "Surface",
    "TileCut",
    "TilingResult",
    "calculate_tiling",
    "format_report",
    "DEFAULT_POWER_W",
    "ConsumptionPoint",
    "PointKind",
    "CableRoute",
    "build_route",
    "AMPACITY_A",
    "COPPER_RESISTIVITY_OHM_MM2_PER_M",
    "MAX_VOLTAGE_DROP_PERCENT_DEFAULT",
    "MIN_CROSS_SECTION_LIGHTING_MM2",
    "MIN_CROSS_SECTION_POWER_MM2",
    "STANDARD_BREAKER_RATINGS_A",
    "STANDARD_CROSS_SECTIONS_MM2",
    "VOLTAGE_V",
    "PhaseType",
    "calculate_current_a",
    "rcd_required_for_kinds",
    "select_breaker_rating_a",
    "select_cross_section_mm2",
    "voltage_drop_percent",
    "Group",
    "GroupCalculation",
    "calculate_group",
    "WiringPlan",
    "format_wiring_report",
    "Component",
    "ComponentKind",
    "Footprint",
    "Pin",
    "ComponentUnit",
    "CONNECTOR_PITCH_MM",
    "DIP_PITCH_MM",
    "DIP_ROW_SPACING_MM",
    "SOIC_PITCH_MM",
    "SOIC_ROW_SPACING_MM",
    "THT_RESISTOR_SPACING_MM",
    "connector_footprint",
    "dip_footprint",
    "soic_footprint",
    "to92_footprint",
    "two_pin_footprint",
    "Net",
    "NetKind",
    "Netlist",
    "PinRef",
    "ShortCircuit",
    "CLEARANCE_TABLE_MM",
    "DEFAULT_COPPER_THICKNESS_UM",
    "DEFAULT_TEMPERATURE_RISE_C",
    "MAX_TRACK_VOLTAGE_DROP_PERCENT_DEFAULT",
    "MIN_TRACK_WIDTH_MM",
    "Layer",
    "min_clearance_mm",
    "required_track_width_mm",
    "track_resistance_ohm",
    "track_voltage_drop_v",
    "PCB_COPPER_RESISTIVITY_OHM_MM2_PER_M",
    "Board",
    "Placement",
    "Track",
    "Via",
    "build_track",
    "ClearanceViolation",
    "RatsnestGap",
    "clearance_violations",
    "unrouted_connections",
    "format_board_report",
    "Coverage",
    "MaterialCategory",
    "MaterialSpec",
    "PriceInfo",
    "MaterialDatabase",
    "build_default_database",
    "SelectionCriteria",
    "SelectionResult",
    "select_materials",
    "select_tile_adhesive_for_balcony",
    "ThermalComparison",
    "ThermalLayerOption",
    "compare_for_thermal_resistance",
    "conductor_resistance_ohm",
    "thermal_layer_option",
    "DEFAULT_MAINTENANCE_FACTOR",
    "DEFAULT_UTILIZATION_FACTOR",
    "RECOMMENDED_LUX",
    "RoomPurpose",
    "FixtureKind",
    "LightFixture",
    "LightingPlan",
    "fixtures_needed",
    "illuminance_lux",
    "lighting_group",
    "plan_lighting",
    "required_luminous_flux_lm",
    "AIR_CHANGES_PER_HOUR",
    "AIR_DENSITY_KG_M3",
    "DEFAULT_FRICTION_FACTOR",
    "MAX_RECOMMENDED_VELOCITY_M_S",
    "MINIMUM_EXHAUST_M3_H",
    "STANDARD_FANS",
    "STANDARD_ROUND_DUCT_DIAMETERS_MM",
    "VentilatedRoomKind",
    "Duct",
    "DuctShape",
    "air_velocity_m_s",
    "build_duct",
    "pressure_loss_pa",
    "required_airflow_m3_h",
    "select_fan",
    "select_round_duct_diameter_mm",
    "AIR_VOLUMETRIC_HEAT_CAPACITY_WH_M3K",
    "DEFAULT_INDOOR_TEMP_C",
    "DESIGN_OUTDOOR_TEMP_C",
    "STANDARD_AC_POWERS_KW",
    "STANDARD_RADIATOR_POWERS_W",
    "ClimateZone",
    "BuildingElement",
    "HeatBalance",
    "select_ac_power_kw",
    "select_radiator_power_w",
    "transmission_heat_loss_w",
    "ventilation_heat_loss_w",
    "RSE_WALL_M2K_W",
    "RSI_WALL_M2K_W",
    "WT2021_MAX_U_WALL_W_M2K",
    "InsulationCheck",
    "WallLayer",
    "check_against_wt2021",
    "condensation_risk_warnings",
    "dew_point_c",
    "insulation_cost_per_m2",
    "layer_interface_temperatures_c",
    "required_insulation_thickness_m",
    "wall_thermal_resistance_m2k_w",
    "wall_u_value_w_m2k",
    "COVERAGE_AREA_M2",
    "MAX_SPACING_M",
    "WALL_CLEARANCE_M",
    "DetectorKind",
    "FireDetector",
    "auto_place_detectors",
    "detectors_needed",
    "loop_length_m",
    "place_detectors_along_contour",
    "Face",
    "Point3",
    "extrude_contour_walls",
    "extrude_flat_faces",
    "Opening",
    "OpeningKind",
    "Wall3D",
    "Slab",
    "Roof",
    "RoofType",
    "build_gable_roof",
    "build_shed_roof",
    "Building",
    "Storey",
    "contours_match",
    "exterior_envelope_area_m2",
    "room_volume_m3",
    "wall_material_costs_pln",
    "wall_material_volumes_m3",
    "Mesh",
    "build_room_mesh",
    "DEFAULT_SAFETY_FACTOR",
    "ELASTIC_MODULUS_MPA",
    "GRAVITY_M_S2",
    "MAX_DEFLECTION_RATIO",
    "elastic_modulus_mpa_for",
    "AngleProfile",
    "ChannelProfile",
    "FlatBarProfile",
    "IBeamProfile",
    "RectTubeProfile",
    "RoundBarProfile",
    "RoundTubeProfile",
    "StructProfile",
    "Beam",
    "BeamCheckResult",
    "LoadScheme",
    "Structure",
    "bending_moment_max_nmm",
    "bending_stress_mpa",
    "evaluate_beam",
    "max_deflection_mm",
    "Shaft",
    "disk_moment_of_inertia_kg_m2",
    "ring_moment_of_inertia_kg_m2",
    "wheel_moment_of_inertia_kg_m2",
    "BeltTransmission",
    "DirectTransmission",
    "GearboxTransmission",
    "Transmission",
    "power_w",
    "rad_s_to_rpm",
    "rpm_to_rad_s",
    "torque_nm",
    "Motor",
    "MotorKind",
    "current_under_load_a",
    "heat_dissipation_w",
    "motor_pcb_track_width_mm",
    "power_input_w",
    "motor_to_consumption_point",
    "torque_constant_nm_per_a",
    "available_force_n",
    "can_move_mass",
    "required_force_to_move_n",
    "time_to_speed_s",
    "wheel_angular_velocity_rad_s",
    "wheel_linear_speed_m_s",
    "format_beam_report",
    "format_drive_report",
    "format_structure_report",
    "OutputType",
    "Sensor",
    "SensorKind",
    "Actuator",
    "ActuatorKind",
    "ActuatorLike",
    "actuator_current_a",
    "actuator_kind_label",
    "actuator_voltage_v",
    "Controller",
    "ControllerCheckResult",
    "ControllerSpec",
    "PinIssue",
    "Action",
    "Condition",
    "MachineState",
    "Rule",
    "Scenario",
    "TimerSpec",
    "apply_step",
    "expired_timers",
    "find_dead_end_states",
    "find_forbidden_rule_violations",
    "SimulationLogEntry",
    "SimulationResult",
    "SimulationStep",
    "run_scenario",
    "GateSystem",
    "build_gate_scenario",
    "gate_cycle_time_s",
    "recommended_timeout_s",
    "format_controller_report",
    "format_gate_system_report",
    "format_scenario_report",
    "format_simulation_report",
]
